In [1]:
import pandas as pd

In [2]:
df_log_existants = pd.read_csv('~/code/enedis-wagon/data/ademe-logements-existants.csv', delimiter=',')

/var/folders/y9/7s7sqqss253gzk6n0ct2by0r0000gn/T/ipykernel_5669/2477875483.py:1: DtypeWarning: Columns (11,12,29,30,112,190,191,192,193,218,219,220,221,222,226,237) have mixed types. Specify dtype option on import or set low_memory=False.
  df_log_existants = pd.read_csv('~/code/enedis-wagon/data/ademe-logements-existants.csv', delimiter=',')

In [3]:
df_enedis = pd.read_csv('~/code/enedis-wagon/data/enedis_13_citycode.csv', delimiter=',')

In [4]:
df_log_existants.head()

,N°DPE,Date_réception_DPE,Date_établissement_DPE,Date_visite_diagnostiqueur,Modèle_DPE,N°_DPE_remplacé,Date_fin_validité_DPE,Version_DPE,N°_DPE_immeuble_associé,Appartement_non_visité_(0/1),...,Type_générateur_froid,Surface_climatisée,Type_énergie_climatisation,Catégorie_ENR,Electricité_PV_autoconsommée,Système_production_électricité_origine_renouvelable,Présence_production_PV_(0/1),Production_électricité_PV_(kWhep/an),Surface_totale_capteurs_photovoltaïque,Nombre_module
0,2113E1018248X,2022-01-03,2021-11-21,2021-11-21,DPE 3CL 2021 méthode logement,NaN,2031-11-20,1.1,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,Solaire Photovoltaïque,1.0,0.0,NaN,NaN
1,2313E1088013G,2023-03-31,2023-03-23,2023-03-23,DPE 3CL 2021 méthode logement,NaN,2033-03-22,2.2,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,Solaire Photovoltaïque,0.0,0.0,NaN,NaN
2,2113E1017999I,2022-01-03,2021-11-30,2021-11-30,DPE 3CL 2021 méthode logement,NaN,2031-11-29,1.1,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,Solaire Photovoltaïque,1.0,0.0,NaN,NaN
3,2113E1018033Q,2022-01-03,2021-12-04,2021-11-25,DPE 3CL 2021 méthode logement,NaN,2031-12-03,1.1,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,Solaire Photovoltaïque,1.0,0.0,NaN,NaN
4,2113E1018028L,2022-01-03,2021-11-30,2021-11-30,DPE 3CL 2021 méthode logement,NaN,2031-11-29,1.1,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,Solaire Photovoltaïque,1.0,0.0,NaN,NaN

In [48]:
# Create a dictionary that maps DPE values to integers
dpe_mapping = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7}

# Create a new column 'DPE_numeric' that maps the DPE values to integers
df_log_existants_2022['DPE_numeric'] = df_log_existants_2022['Etiquette_DPE'].map(dpe_mapping)

/var/folders/y9/7s7sqqss253gzk6n0ct2by0r0000gn/T/ipykernel_5669/1090359067.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_log_existants_2022['DPE_numeric'] = df_log_existants_2022['Etiquette_DPE'].map(dpe_mapping)

In [44]:
df_log_existants['Date_réception_DPE'] = pd.to_datetime(df_log_existants['Date_réception_DPE'], errors='coerce')

In [45]:
df_log_existants['Year_reception_DPE'] = df_log_existants['Date_réception_DPE'].dt.year

In [46]:
df_log_existants_2022 = df_log_existants[df_log_existants['Year_reception_DPE'] == 2022]

In [47]:
df_log_existants_2022.head()

,N°DPE,Date_réception_DPE,Date_établissement_DPE,Date_visite_diagnostiqueur,Modèle_DPE,N°_DPE_remplacé,Date_fin_validité_DPE,Version_DPE,N°_DPE_immeuble_associé,Appartement_non_visité_(0/1),...,Type_énergie_climatisation,Catégorie_ENR,Electricité_PV_autoconsommée,Système_production_électricité_origine_renouvelable,Présence_production_PV_(0/1),Production_électricité_PV_(kWhep/an),Surface_totale_capteurs_photovoltaïque,Nombre_module,DPE_numeric,Year_reception_DPE
0,2113E1018248X,2022-01-03,2021-11-21,2021-11-21,DPE 3CL 2021 méthode logement,NaN,2031-11-20,1.1,NaN,NaN,...,NaN,NaN,1.0,Solaire Photovoltaïque,1.0,0.0,NaN,NaN,4,2022
2,2113E1017999I,2022-01-03,2021-11-30,2021-11-30,DPE 3CL 2021 méthode logement,NaN,2031-11-29,1.1,NaN,NaN,...,NaN,NaN,1.0,Solaire Photovoltaïque,1.0,0.0,NaN,NaN,4,2022
3,2113E1018033Q,2022-01-03,2021-12-04,2021-11-25,DPE 3CL 2021 méthode logement,NaN,2031-12-03,1.1,NaN,NaN,...,NaN,NaN,1.0,Solaire Photovoltaïque,1.0,0.0,NaN,NaN,4,2022
4,2113E1018028L,2022-01-03,2021-11-30,2021-11-30,DPE 3CL 2021 méthode logement,NaN,2031-11-29,1.1,NaN,NaN,...,NaN,NaN,1.0,Solaire Photovoltaïque,1.0,0.0,NaN,NaN,3,2022
5,2113E1018171Y,2022-01-03,2021-11-25,2021-11-25,DPE 3CL 2021 méthode logement,NaN,2031-11-24,1.1,NaN,NaN,...,NaN,NaN,1.0,Solaire Photovoltaïque,1.0,0.0,NaN,NaN,4,2022

In [49]:
# Display the first few rows of the DataFrame, including the 'Etiquette_DPE' and 'DPE_numeric' columns
df_log_existants_2022[['Etiquette_DPE', 'DPE_numeric']].head()

  Etiquette_DPE  DPE_numeric
0             D            4
2             D            4
3             D            4
4             C            3
5             D            4

In [50]:
# Create a new DataFrame with the 'DPE_numeric', 'Etiquette_DPE', and 'Identifiant__BAN' columns
df_simple_2022 = pd.DataFrame({
    'DPE_numeric': df_log_existants_2022['DPE_numeric'],
    'Etiquette_DPE': df_log_existants_2022['Etiquette_DPE'],
    'Identifiant__BAN': df_log_existants_2022['Identifiant__BAN']
})

In [52]:
df_simple_2022.head(10)

    DPE_numeric Etiquette_DPE  Identifiant__BAN
0             4             D        13041_0755
2             4             D  13216_6965_00204
3             4             D  13004_3663_00009
4             3             C        13078_A003
5             4             D        13056_1715
6             4             D        13078_A003
8             3             C  13050_0290_00009
9             5             E  13206_7002_00056
12            3             C      13019_2yeziq
14            3             C        13007_0230

In [53]:
df_simple_2022.shape

(76303, 3)

In [54]:
# Calculate the average DPE per id_ban and round it to the nearest integer
df_average_dpe_per_id_ban_2022 = df_simple_2022.groupby('Identifiant__BAN')['DPE_numeric'].mean().round().reset_index()

In [55]:
df_average_dpe_per_id_ban_2022.shape

(33833, 2)

In [56]:
df_average_dpe_per_id_ban_2022.head()

   Identifiant__BAN  DPE_numeric
0        13001_0003          4.0
1  13001_0003_00013          4.0
2  13001_0003_00021          3.0
3  13001_0003_00023          3.0
4  13001_0003_00025          4.0

In [57]:
# Create a reverse mapping dictionary that maps integers to DPE values
reverse_dpe_mapping = {1.0: 'A', 2.0: 'B', 3.0: 'C', 4.0: 'D', 5.0: 'E', 6.0: 'F', 7.0: 'G'}

# Create a new column 'Etiquette_DPE_rounded' that maps the rounded DPE values to their corresponding letters
df_average_dpe_per_id_ban_2022['Etiquette_DPE_per_id_ban'] = df_average_dpe_per_id_ban_2022['DPE_numeric'].map(reverse_dpe_mapping)

In [58]:
df_average_dpe_per_id_ban_2022.head()

   Identifiant__BAN  DPE_numeric Etiquette_DPE_per_id_ban
0        13001_0003          4.0                        D
1  13001_0003_00013          4.0                        D
2  13001_0003_00021          3.0                        C
3  13001_0003_00023          3.0                        C
4  13001_0003_00025          4.0                        D

In [59]:
df_average_dpe_per_id_ban_2022.to_csv('dpe_groupby_2022',index=False)